version: "3.7"

services:
  clean-dash:
    build:
      context: .
    image: clean-dash:1.0.0
    container_name: clean-dash
    ports:
      - "8089:8090"
    environment:
      - TARGET=LIVE
    restart: unless-stopped
